CREATE SEQUENCE "PUBLIC"."HIBERNATE_SEQUENCE" START WITH 8;

CREATE CACHED TABLE EMPLOYEE(
    "ID" BIGINT NOT NULL,
    "NAME" VARCHAR(255)
);

ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_ID_PK PRIMARY KEY("ID");

CREATE CACHED TABLE MENU(
    "ID" BIGINT NOT NULL,
    "ITEM_COST" DOUBLE NOT NULL,
    "ITEM_NAME" VARCHAR(255)
);

ALTER TABLE MENU ADD CONSTRAINT MENU_ID_PK PRIMARY KEY("ID");

CREATE CACHED TABLE ORDERS(
    "ID" BIGINT NOT NULL,

    "KITCHEN_TIME" TIMESTAMP,
    "COMPLETED_TIME" TIMESTAMP,
    "CREATED_TIME" TIMESTAMP,

    "DESTINATION" VARCHAR(255),
    "EMPLOYEE" VARCHAR(255),
    "ORDER_NOTES" VARCHAR(255),
    "PICK_UP_ORDER" BOOLEAN,
    "STATUS" VARCHAR(255)
);

ALTER TABLE ORDERS ADD CONSTRAINT ORDERS_ID_PK PRIMARY KEY("ID");

CREATE CACHED TABLE ORDER_ITEM(
    "ID" BIGINT NOT NULL,
    "QUANTITY" INTEGER,
    "MENU_ITEM_ID" BIGINT,
    "ORDER_ID" BIGINT
);

ALTER TABLE ORDER_ITEM ADD CONSTRAINT ORDER_ITEM_ID_PK PRIMARY KEY("ID");
ALTER TABLE ORDER_ITEM ADD CONSTRAINT ORDER_ITEM_MENU_ITEM_FK FOREIGN KEY ("MENU_ITEM_ID") REFERENCES MENU("ID") NOCHECK;
ALTER TABLE ORDER_ITEM ADD CONSTRAINT ORDER_ITEM_ORDER_FK FOREIGN KEY ("ORDER_ID") REFERENCES ORDERS("ID") NOCHECK;

CREATE CACHED TABLE RESERVATION(
    "ID" BIGINT NOT NULL,
    "NAME" VARCHAR(255) NOT NULL,
    "PHONE_NUMBER" VARCHAR(255) NOT NULL,
    "NUMBER_OF_PEOPLE" INTEGER NOT NULL,
    "DATE" DATE NOT NULL,
    "TIME" TIME NOT NULL
);

ALTER TABLE RESERVATION ADD CONSTRAINT RESERVATION_ID_PK PRIMARY KEY("ID");

